import React from "react";

import { SubHeading } from "../../components";

const FindUs = () => (
  <div className="app__bg app__wrapper section__padding" id="contact">
    <div className="app__wrapper_info">
      <SubHeading title="Contact" />
      <h1 className="headtext__cormorant" style={{ marginBottom: "3rem" }}>
        Find Us
      </h1>

      {/* Displaying contact information */}
      <div className="app__wrapper-content">
        <p className="p__cormorant" style={{ color: "#DCCA87" }}>
          Address:
        </p>
        <p className="p__opensans">
          4271 Sheppard Avenue East Unit #1. Scarborough, ON. M1S 4G4
        </p>

        <br></br>
        <p className="p__cormorant" style={{ color: "#DCCA87" }}>
          Opening Hours:
        </p>

        <p className="p__opensans">Monday to Sunday: 11am - 9pm</p>

        <br></br>
        <p className="p__cormorant" style={{ color: "#DCCA87" }}>
          Phone:
        </p>

        <p className="p__opensans">416-297-1581</p>
      </div>

      {/* Redirecting to Google maps if user clicks the "Visit Us" button */}
      <a href="https://google.com/maps/place/Beef+Noodle+Restaurant/@43.7855369,-79.2762483,15z/data=!4m2!3m1!1s0x0:0x7323e4958b94e0a4?sa=X&ved=2ahUKEwiDi56zvpX8AhVMi3IEHZ3iBRUQ_BJ6BAhLEAg">
        <button className="custom__button" style={{ marginTop: "2rem" }}>
          Visit Us
        </button>
      </a>
    </div>

    <div className="app__wrapper_img">
      {/* Setting up the Google Maps, generated by maps-generator.com */}
      <iframe
        title="Beef Noodle Restaurant"
        width="816"
        height="547"
        frameBorder="0"
        scrolling="no"
        marginHeight="0"
        marginWidth="0"
        id="gmap_canvas"
        src="https://maps.google.com/maps?width=816&amp;height=547&amp;hl=en&amp;q=Beef%20Noodle%20Restaurant%204G4+(Beef%20Noodle%20Restaurant)&amp;t=&amp;z=16&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
      ></iframe>
    </div>
  </div>
);

export default FindUs;
